from dotenv import load_dotenv
import os

load_dotenv()

class Config:
    """
    Configuration class to manage environment variables.
    """
    GOOGLE_CREDENTIALS_TYPE = os.getenv("GOOGLE_CREDENTIALS_TYPE")
    GOOGLE_CREDENTIALS_PROJECT_ID = os.getenv("GOOGLE_CREDENTIALS_PROJECT_ID")
    GOOGLE_CREDENTIALS_PRIVATE_KEY_ID = os.getenv("GOOGLE_CREDENTIALS_PRIVATE_KEY_ID")
    GOOGLE_CREDENTIALS_PRIVATE_KEY = os.getenv("GOOGLE_CREDENTIALS_PRIVATE_KEY")
    GOOGLE_CREDENTIALS_CLIENT_EMAIL = os.getenv("GOOGLE_CREDENTIALS_CLIENT_EMAIL")
    GOOGLE_CREDENTIALS_CLIENT_ID = os.getenv("GOOGLE_CREDENTIALS_CLIENT_ID")
    GOOGLE_CREDENTIALS_AUTH_URI = os.getenv("GOOGLE_CREDENTIALS_AUTH_URI")
    GOOGLE_CREDENTIALS_TOKEN_URI = os.getenv("GOOGLE_CREDENTIALS_TOKEN_URI")
    GOOGLE_CREDENTIALS_AUTH_PROVIDER_X509_CERT_URL = os.getenv("GOOGLE_CREDENTIALS_AUTH_PROVIDER_X509_CERT_URL")
    GOOGLE_CREDENTIALS_CLIENT_X509_CERT_URL = os.getenv("GOOGLE_CREDENTIALS_CLIENT_X509_CERT_URL")
    GOOGLE_CREDENTIALS_UNIVERSE_DOMAIN = os.getenv("GOOGLE_CREDENTIALS_UNIVERSE_DOMAIN")
    
